#!/usr/bin/python
from hosted import device, node, config
from time import sleep
import serial

config.restart_on_update()

ser = serial.Serial ("/dev/ttyS0", 115200, timeout=0.5)
ser.read(ser.inWaiting())                  # clear buffer
while True:
    received_data = ser.readline()        # read serial (Serial.println(<0-1024>))
    if received_data == '':
        continue

    try:
        received_data = int(received_data)
        node.send('/state:%d' % received_data)
    except:
        continue

    sleep(0.03)
