#!/usr/bin/python
from hosted import device, node, config
from time import sleep
import serial

config.restart_on_update()

ser = serial.Serial ("/dev/ttyS0", 115200)
while True:
    received_data = ser.read()              #read serial port
    print(received_data)                   #print received data
    sleep(0.03)
    node.send('/state:%d' % 9)

